services:
  typescript-app:
    build: .
    container_name: ts_runner
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/dist
    working_dir: /app/src
    command: nodemon --exec ts-node index.ts --ext ts
    stdin_open: true
    tty: true